#!/usr/bin/env python3
"""Reject process-language traces in publication-facing status documents."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List, Tuple


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PATHS = [
    ROOT / "docs" / "AUTOFIT_V72_EVIDENCE_MASTER_20260217.md",
    ROOT / "docs" / "BLOCK3_MODEL_STATUS.md",
    ROOT / "docs" / "BLOCK3_RESULTS.md",
]

FORBIDDEN_PATTERNS = [
    "as an ai",
    "llm-generated",
    "generated by llm",
    "generated by an ai",
    "assistant-generated",
    "agent-generated",
    "this report was generated by",
    "handoff for next agent",
    "for the next agent",
]


def _scan(path: Path) -> List[Tuple[int, str]]:
    findings: List[Tuple[int, str]] = []
    if not path.exists():
        return findings
    for idx, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        low = line.lower()
        for pat in FORBIDDEN_PATTERNS:
            if pat in low:
                findings.append((idx, line.strip()))
                break
    return findings


def main() -> None:
    parser = argparse.ArgumentParser(description="Style guard for docs wording.")
    parser.add_argument(
        "--paths",
        type=str,
        default=",".join(str(p) for p in DEFAULT_PATHS),
        help="Comma-separated document paths to scan.",
    )
    args = parser.parse_args()

    paths = [Path(p.strip()) for p in args.paths.split(",") if p.strip()]
    violations = []
    for p in paths:
        resolved = p if p.is_absolute() else (ROOT / p)
        findings = _scan(resolved)
        for ln, text in findings:
            violations.append((resolved, ln, text))

    if violations:
        print("Style guard FAILED:")
        for path, ln, text in violations:
            print(f"  {path}:{ln}: {text}")
        raise SystemExit(2)

    print("Style guard PASS")
    for p in paths:
        resolved = p if p.is_absolute() else (ROOT / p)
        print(f"  - {resolved}")


if __name__ == "__main__":
    main()
